export {
	faAngleDown,
	faAngleDoubleRight,
	faBolt,
	faBug,
	faCheck,
	faCheckDouble,
	faCircle,
	faEllipsisH,
	faEnvelope,
	faExclamationCircle,
	faExclamationTriangle,
	faFutbol,
	faLock,
	faPlus,
	faShieldAlt,
	faUser,
	faWindowClose,
} from '@fortawesome/free-solid-svg-icons'
