export {
	faAngleDown,
	faAngleDoubleRight,
	faBolt,
	faCheck,
	faCheckDouble,
	faCircle,
	faEllipsisH,
	faEnvelope,
	faExclamationCircle,
	faExclamationTriangle,
	faFutbol,
	faLock,
	faShieldAlt,
	faUser,
} from '@fortawesome/free-solid-svg-icons'
